In [3]:
import pandas as pd

In [2]:
df_auto = pd.read_csv('data_only_auto.csv')
df_manual = pd.read_csv('data_only_manual.csv')

In [3]:
df_auto = df_auto.rename(columns = {'Unnamed: 0': 'index'})
df_manual = df_manual.rename(columns = {'Unnamed: 0': 'index'})

In [4]:
df_manual

,index,Unnamed: 0.1,Unnamed: 0.1.1,ISCO,major_job,job,position,location,description,entities_manual_label
0,0,0,0,21,SCIENCE AND ENGINEERING PROFESSIONALS,physicist,Accelerator Physicist id54315,"Villigen PSI, Aargau",[' You have an academic degree in physics or e...,"[{'entity': physics, 'label': 'KNOWLEDGE'}, {'..."
1,1,1,1,21,SCIENCE AND ENGINEERING PROFESSIONALS,physicist,Applied Physicist (Computing) (EP-LBC-2021-125...,Geneva,[' Be in charge of the development of applicat...,"[{'entity': Python, 'label': 'SKILL'}, {'entit..."
2,2,2,2,21,SCIENCE AND ENGINEERING PROFESSIONALS,physicist,Accelerator Physicist (BE-ABP-LNO-2021-122-LD)...,Geneva,[' Contribute to the maintenance and developme...,"[{'entity': rel=""nofollow"">http://madx.web.cer..."
3,3,3,3,21,SCIENCE AND ENGINEERING PROFESSIONALS,physicist,Medical Devices Physicist,"Newton, Cambridgeshire",[' Agency: Newton Colmore Consulting Reference...,[]
4,4,4,4,21,SCIENCE AND ENGINEERING PROFESSIONALS,physicist,Fluidics Physicist,Cambridge,[' Agency: Newton Colmore Consulting Reference...,[]
...,...,...,...,...,...,...,...,...,...,...
4407,1907,4407,4407,91,CLEANERS AND HELPERS,washer,Dishwasher employee,"Amsterdam, Noord-Holland",[' Eye for detail and through! You have a real...,[]
4408,1908,4408,4408,91,CLEANERS AND HELPERS,washer,Detail Technician/Fleet Washer/Truck Washer/Au...,Michigan,[' Paid Training Direct Care (health) Paid Vac...,"[{'entity': driver's license, 'label': 'KNOWLE..."
4409,1909,4409,4409,91,CLEANERS AND HELPERS,washer,Detail Technician/Fleet Washer/Truck Washer/Au...,"Warszawa, Mazowieckie",[' Paid Training Direct Care (health) Paid Vac...,"[{'entity': driver's license, 'label': 'KNOWLE..."
4410,1910,4410,4410,91,CLEANERS AND HELPERS,washer,Detail Technician/Fleet Washer/Truck Washer/Au...,Michigan,[' Paid Training Direct Care (health) Paid Vac...,"[{'entity': driver's license, 'label': 'KNOWLE..."
4411,1911,4411,4411,91,CLEANERS AND HELPERS,washer,Horeca Medewerker Afwas/Stewarding / Hospitali...,"Eindhoven, Noord-Brabant",[' Enthousiast en energiek Eerlijk Flexibel in...,[]

In [39]:
data_final = df_auto.merge(df_manual[['index', 'entities_manual_label']], on = 'index', how = 'inner')

In [40]:
data_final

,index,ISCO,major_job,job,position,location,description,entities_auto_label,entities_manual_label
0,0,21,SCIENCE AND ENGINEERING PROFESSIONALS,physicist,Accelerator Physicist id54315,"Villigen PSI, Aargau",[' You have an academic degree in physics or e...,(),"[{'entity': physics, 'label': 'KNOWLEDGE'}, {'..."
1,0,21,SCIENCE AND ENGINEERING PROFESSIONALS,physicist,Accelerator Physicist id54315,"Villigen PSI, Aargau",[' You have an academic degree in physics or e...,(),"[{'entity': RICS, 'label': 'SKILL'}, {'entity'..."
2,0,21,SCIENCE AND ENGINEERING PROFESSIONALS,physicist,Accelerator Physicist id54315,"Villigen PSI, Aargau",[' You have an academic degree in physics or e...,(),"[{'entity': CIS, 'label': 'SKILL'}, {'entity':..."
3,1,21,SCIENCE AND ENGINEERING PROFESSIONALS,physicist,Applied Physicist (Computing) (EP-LBC-2021-125...,Geneva,[' Be in charge of the development of applicat...,"(Python, Python)","[{'entity': Python, 'label': 'SKILL'}, {'entit..."
4,1,21,SCIENCE AND ENGINEERING PROFESSIONALS,physicist,Applied Physicist (Computing) (EP-LBC-2021-125...,Geneva,[' Be in charge of the development of applicat...,"(Python, Python)",[]
...,...,...,...,...,...,...,...,...,...
4407,1907,22,HEALTH PROFESSIONALS,veterinary surgeon,Locum Veterinary Surgeon,"Isle of Dogs, East London",[' Type: Small Animal Start Date: 20th Decembe...,(),[]
4408,1908,22,HEALTH PROFESSIONALS,veterinary surgeon,Veterinary Surgeon,"Middlesbrough, North Yorkshire","[' Allocated CPD funding of 37.5 hours ', ' 5 ...",(),"[{'entity': driver's license, 'label': 'KNOWLE..."
4409,1909,22,HEALTH PROFESSIONALS,veterinary surgeon,Permanent Veterinary Surgeon,"Harrogate, North Yorkshire","["" Experienced required: New Graduate level to...",(),"[{'entity': driver's license, 'label': 'KNOWLE..."
4410,1910,22,HEALTH PROFESSIONALS,veterinary surgeon,Locum Veterinary Surgeon,Lancaster,[' Type: Small Animal Start Date: 6th January ...,(),"[{'entity': driver's license, 'label': 'KNOWLE..."
4411,1911,22,HEALTH PROFESSIONALS,veterinary surgeon,Veterinary Surgeon,"Beckenham, Greater London",[' Allocated CPD funding of Â£1000 & 37.5 hours...,(),[]

In [41]:
for index, row in data_final.iterrows():
    if row.entities_auto_label == '()' and row.entities_manual_label == '[]':
        data_final.drop(index, inplace=True)

In [45]:
data_final = data_final.reset_index().drop(['level_0', 'index'], axis = 1)

In [2]:
data_final.to_csv('data_final_raw.csv')

NameError: name 'data_final' is not defined

In [48]:
data_final

,ISCO,major_job,job,position,location,description,entities_auto_label,entities_manual_label
0,21,SCIENCE AND ENGINEERING PROFESSIONALS,physicist,Accelerator Physicist id54315,"Villigen PSI, Aargau",[' You have an academic degree in physics or e...,(),"[{'entity': physics, 'label': 'KNOWLEDGE'}, {'..."
1,21,SCIENCE AND ENGINEERING PROFESSIONALS,physicist,Accelerator Physicist id54315,"Villigen PSI, Aargau",[' You have an academic degree in physics or e...,(),"[{'entity': RICS, 'label': 'SKILL'}, {'entity'..."
2,21,SCIENCE AND ENGINEERING PROFESSIONALS,physicist,Accelerator Physicist id54315,"Villigen PSI, Aargau",[' You have an academic degree in physics or e...,(),"[{'entity': CIS, 'label': 'SKILL'}, {'entity':..."
3,21,SCIENCE AND ENGINEERING PROFESSIONALS,physicist,Applied Physicist (Computing) (EP-LBC-2021-125...,Geneva,[' Be in charge of the development of applicat...,"(Python, Python)","[{'entity': Python, 'label': 'SKILL'}, {'entit..."
4,21,SCIENCE AND ENGINEERING PROFESSIONALS,physicist,Applied Physicist (Computing) (EP-LBC-2021-125...,Geneva,[' Be in charge of the development of applicat...,"(Python, Python)",[]
...,...,...,...,...,...,...,...,...
3502,22,HEALTH PROFESSIONALS,veterinary surgeon,Veterinary Surgeon,England,[' Allocated CPD funding of 37.5 hours Excelle...,(),"[{'entity': driving licence, 'label': 'KNOWLED..."
3503,22,HEALTH PROFESSIONALS,veterinary surgeon,Permanent Veterinary Surgeon,"Cricklewood, North West London",[' Type: Small Animal Hours: Monday - Friday 4...,(),"[{'entity': driver's license, 'label': 'KNOWLE..."
3504,22,HEALTH PROFESSIONALS,veterinary surgeon,Veterinary Surgeon,"Middlesbrough, North Yorkshire","[' Allocated CPD funding of 37.5 hours ', ' 5 ...",(),"[{'entity': driver's license, 'label': 'KNOWLE..."
3505,22,HEALTH PROFESSIONALS,veterinary surgeon,Permanent Veterinary Surgeon,"Harrogate, North Yorkshire","["" Experienced required: New Graduate level to...",(),"[{'entity': driver's license, 'label': 'KNOWLE..."
3506,22,HEALTH PROFESSIONALS,veterinary surgeon,Locum Veterinary Surgeon,Lancaster,[' Type: Small Animal Start Date: 6th January ...,(),"[{'entity': driver's license, 'label': 'KNOWLE..."

In [7]:
df = pd.read_csv('data_final_raw.csv')

In [9]:
from ast import literal_eval
df.entities_auto_label= df.entities_auto_label.astype(list)

TypeError: dtype '<class 'list'>' not understood

In [10]:
df

,Unnamed: 0,ISCO,major_job,job,position,location,description,entities_auto_label,entities_manual_label
0,0,21,SCIENCE AND ENGINEERING PROFESSIONALS,physicist,Accelerator Physicist id54315,"Villigen PSI, Aargau",[' You have an academic degree in physics or e...,(),"[{'entity': physics, 'label': 'KNOWLEDGE'}, {'..."
1,1,21,SCIENCE AND ENGINEERING PROFESSIONALS,physicist,Accelerator Physicist id54315,"Villigen PSI, Aargau",[' You have an academic degree in physics or e...,(),"[{'entity': RICS, 'label': 'SKILL'}, {'entity'..."
2,2,21,SCIENCE AND ENGINEERING PROFESSIONALS,physicist,Accelerator Physicist id54315,"Villigen PSI, Aargau",[' You have an academic degree in physics or e...,(),"[{'entity': CIS, 'label': 'SKILL'}, {'entity':..."
3,3,21,SCIENCE AND ENGINEERING PROFESSIONALS,physicist,Applied Physicist (Computing) (EP-LBC-2021-125...,Geneva,[' Be in charge of the development of applicat...,"(Python, Python)","[{'entity': Python, 'label': 'SKILL'}, {'entit..."
4,4,21,SCIENCE AND ENGINEERING PROFESSIONALS,physicist,Applied Physicist (Computing) (EP-LBC-2021-125...,Geneva,[' Be in charge of the development of applicat...,"(Python, Python)",[]
...,...,...,...,...,...,...,...,...,...
3502,3502,22,HEALTH PROFESSIONALS,veterinary surgeon,Veterinary Surgeon,England,[' Allocated CPD funding of 37.5 hours Excelle...,(),"[{'entity': driving licence, 'label': 'KNOWLED..."
3503,3503,22,HEALTH PROFESSIONALS,veterinary surgeon,Permanent Veterinary Surgeon,"Cricklewood, North West London",[' Type: Small Animal Hours: Monday - Friday 4...,(),"[{'entity': driver's license, 'label': 'KNOWLE..."
3504,3504,22,HEALTH PROFESSIONALS,veterinary surgeon,Veterinary Surgeon,"Middlesbrough, North Yorkshire","[' Allocated CPD funding of 37.5 hours ', ' 5 ...",(),"[{'entity': driver's license, 'label': 'KNOWLE..."
3505,3505,22,HEALTH PROFESSIONALS,veterinary surgeon,Permanent Veterinary Surgeon,"Harrogate, North Yorkshire","["" Experienced required: New Graduate level to...",(),"[{'entity': driver's license, 'label': 'KNOWLE..."
3506,3506,22,HEALTH PROFESSIONALS,veterinary surgeon,Locum Veterinary Surgeon,Lancaster,[' Type: Small Animal Start Date: 6th January ...,(),"[{'entity': driver's license, 'label': 'KNOWLE..."